FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IGV2ZW50LWZsb3ctYXBiCmRlc2NyaXB0aW9uOiBUaGlzIGlzIGEg\
c2FtcGxlIGFwcGxpY2F0aW9uIGdlbmVyYXRlZCBieSBhcGIgaW5pdApiaW5kYWJsZTogRmFsc2UK\
YXN5bmM6IG9wdGlvbmFsCm1ldGFkYXRhOgogIGRpc3BsYXlOYW1lOiBDbG91ZEV2ZW50IEZsb3cK\
ICBpbWFnZVVybDogImh0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9zandvb2RtYW4v\
ZW52LXZhci1hcGIvbWFzdGVyL2ljb24uc3ZnP3Nhbml0aXplPXRydWUiCiAgcHJvdmlkZXJEaXNw\
bGF5TmFtZTogIlJlZCBIYXQsIEluYy4iCnBsYW5zOgogIC0gbmFtZTogZGVmYXVsdAogICAgZGVz\
Y3JpcHRpb246IFRoaXMgZGVmYXVsdCBwbGFuIGRlcGxveXMgZXZlbnQtZmxvdy1hcGIKICAgIGZy\
ZWU6IFRydWUKICAgIG1ldGFkYXRhOiB7fQogICAgcGFyYW1ldGVyczoKICAgIC0gbmFtZTogYWRt\
aW5fdXNlcgogICAgICB0aXRsZTogT3BlbnNoaWZ0IEFkbWluIFVzZXIKICAgICAgdHlwZTogc3Ry\
aW5nCiAgICAgIHJlcXVpcmVkOiB0cnVlCiAgICAtIG5hbWU6IGFkbWluX3Bhc3N3b3JkCiAgICAg\
IHRpdGxlOiBPcGVuc2hpZnQgQWRtaW4gUGFzc3dvcmQKICAgICAgdHlwZTogc3RyaW5nCiAgICAg\
IGRpc3BsYXlfdHlwZTogcGFzc3dvcmQKICAgICAgcmVxdWlyZWQ6IHRydWUK"

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
RUN chmod -R g=u /opt/{ansible,apb}
USER apb
