FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IGV2ZW50LWZsb3ctYXBiCmRlc2NyaXB0aW9uOiBUaGlzIGlzIGEg\
c2FtcGxlIGFwcGxpY2F0aW9uIGdlbmVyYXRlZCBieSBhcGIgaW5pdApiaW5kYWJsZTogRmFsc2UK\
YXN5bmM6IG9wdGlvbmFsCm1ldGFkYXRhOgogIGRpc3BsYXlOYW1lOiBFdmVudEZsb3cKICBjb25z\
b2xlLm9wZW5zaGlmdC5pby9pY29uQ2xhc3M6IGZhIGZhLXBhcGVyLXBsYW5lCiAgcHJvdmlkZXJE\
aXNwbGF5TmFtZTogIlJlZCBIYXQsIEluYy4iCiAgZGVwZW5kZW5jaWVzOgogICAgLSAiZG9ja2Vy\
LmlvL3N0cmVhbXppL2Vudmlyb25tZW50LXZhcmlhYmxlLW9wZXJhdG9yOmxhdGVzdCIKICAgIC0g\
ImRvY2tlci5pby9zdHJlYW16aS9ldmVudGZsb3ctb3BlcmF0b3I6bGF0ZXN0IgogICAgLSAiZG9j\
a2VyLmlvL3N0cmVhbXppL2V2ZW50Zmxvdy11aTpsYXRlc3QiCnBsYW5zOgogIC0gbmFtZTogZGVm\
YXVsdAogICAgZGVzY3JpcHRpb246IFRoaXMgZGVmYXVsdCBwbGFuIGRlcGxveXMgZXZlbnQtZmxv\
dy1hcGIKICAgIGZyZWU6IFRydWUKICAgIG1ldGFkYXRhOiB7fQogICAgcGFyYW1ldGVyczoKICAg\
IC0gbmFtZTogYWRtaW5fdXNlcgogICAgICB0aXRsZTogT3BlbnNoaWZ0IEFkbWluIFVzZXIKICAg\
ICAgdHlwZTogc3RyaW5nCiAgICAgIHJlcXVpcmVkOiB0cnVlCiAgICAtIG5hbWU6IGFkbWluX3Bh\
c3N3b3JkCiAgICAgIHRpdGxlOiBPcGVuc2hpZnQgQWRtaW4gUGFzc3dvcmQKICAgICAgdHlwZTog\
c3RyaW5nCiAgICAgIGRpc3BsYXlfdHlwZTogcGFzc3dvcmQKICAgICAgcmVxdWlyZWQ6IHRydWUK\
"

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
RUN chmod -R g=u /opt/{ansible,apb}
USER apb
