FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IGV2ZW50LWZsb3ctYXBiCmRlc2NyaXB0aW9uOiBUaGlzIGlzIGEg\
c2FtcGxlIGFwcGxpY2F0aW9uIGdlbmVyYXRlZCBieSBhcGIgaW5pdApiaW5kYWJsZTogRmFsc2UK\
YXN5bmM6IG9wdGlvbmFsCm1ldGFkYXRhOgogIGRpc3BsYXlOYW1lOiBDbG91ZEV2ZW50IEZsb3cK\
ICBjb25zb2xlLm9wZW5zaGlmdC5pby9pY29uQ2xhc3M6IGZhIGZhLXBhcGVyLXBsYW5lCiAgcHJv\
dmlkZXJEaXNwbGF5TmFtZTogIlJlZCBIYXQsIEluYy4iCnBsYW5zOgogIC0gbmFtZTogZGVmYXVs\
dAogICAgZGVzY3JpcHRpb246IFRoaXMgZGVmYXVsdCBwbGFuIGRlcGxveXMgZXZlbnQtZmxvdy1h\
cGIKICAgIGZyZWU6IFRydWUKICAgIG1ldGFkYXRhOiB7fQogICAgcGFyYW1ldGVyczoKICAgIC0g\
bmFtZTogYWRtaW5fdXNlcgogICAgICB0aXRsZTogT3BlbnNoaWZ0IEFkbWluIFVzZXIKICAgICAg\
dHlwZTogc3RyaW5nCiAgICAgIHJlcXVpcmVkOiB0cnVlCiAgICAtIG5hbWU6IGFkbWluX3Bhc3N3\
b3JkCiAgICAgIHRpdGxlOiBPcGVuc2hpZnQgQWRtaW4gUGFzc3dvcmQKICAgICAgdHlwZTogc3Ry\
aW5nCiAgICAgIGRpc3BsYXlfdHlwZTogcGFzc3dvcmQKICAgICAgcmVxdWlyZWQ6IHRydWUK"

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
RUN chmod -R g=u /opt/{ansible,apb}
USER apb
